In [1]:
import numpy as np 
import pandas as pd 
import networkx as nx
from sklearn.neighbors import DistanceMetric
from math import radians

In [2]:
df = pd.read_csv("data/bank_data.csv")
dc = df.copy()

In [3]:
dc['money_and_time_ratio'] = dc['money']/ dc['time (hr)']

In [31]:
dist100near = dc['distance_to_(0,0)'] = (dc['x_coordinate']**2 + dc['y_coordinate']**2)**1/2

In [35]:
dist100near = dc.sort_values(['distance_to_(0,0)'], ascending = True)

In [38]:
dist100near[:100]

,id,x_coordinate,y_coordinate,money,time (hr),money_and_time_ratio,"distance_to_(0,0)","distance_money_time_ratio_(0,0)"
4765,4765,0.038429,0.039438,12900,1.241626,10389.598126,0.001516,6.852997e+06
3936,3936,-0.000257,-0.068866,1100,0.474144,2319.971153,0.002371,9.783637e+05
8789,8789,0.084917,0.003973,93200,0.464666,200574.197761,0.003613,5.550951e+07
1212,1212,0.012560,0.094192,40100,0.290822,137885.026828,0.004515,3.053962e+07
5435,5435,-0.073901,-0.090091,36000,0.919935,39133.207960,0.006789,5.764361e+06
...,...,...,...,...,...,...,...,...
9690,9690,-0.539768,0.112047,400,0.814418,491.148495,0.151952,3.232261e+03
1851,1851,0.293580,0.467744,2700,1.155777,2336.091764,0.152487,1.531997e+04
9406,9406,-0.523337,0.176923,14600,1.361578,10722.848807,0.152592,7.027149e+04
9926,9926,0.409710,-0.371855,31300,0.715459,43748.162564,0.153069,2.858062e+05
9116,9116,-0.309111,-0.459108,7600,1.230316,6177.273229,0.153165,4.033093e+04

In [13]:
sample = dc.iloc[[0,1,2,3,4,5]]
#sample

,id,x_coordinate,y_coordinate,money,time (hr),money_and_time_ratio,"distance_to_(0,0)","distance_money_time_ratio_(0,0)"
0,0,2.851925,1.201712,29700,0.273403,108630.921470,4.788794,22684.399419
1,1,4.150372,-2.654334,6500,0.064040,101499.543603,12.135539,8363.826708
2,2,-1.494092,-1.230419,89400,0.127458,701405.770444,1.873121,374458.338887
3,3,1.271326,-0.088520,96100,1.315029,73078.228687,0.812053,89991.994340
4,4,2.471113,-0.592810,41100,0.164393,250010.909373,3.228911,77428.873274
5,5,-3.169726,-1.965427,36300,1.469407,24703.839127,6.955034,3551.936327

In [7]:
destiance_mon_time_ratio = dc.sort_values(['money_and_time_ratio'], ascending = False)

In [8]:
dc['distance_money_time_ratio_(0,0)'] = dc['money']/ (dc['time (hr)'] * dc['distance_to_(0,0)'])

In [9]:
dc.sort_values(['distance_money_time_ratio_(0,0)'], ascending = False)

,id,x_coordinate,y_coordinate,money,time (hr),money_and_time_ratio,"distance_to_(0,0)","distance_money_time_ratio_(0,0)"
3613,3613,-1.950527,-1.495858,54400,0.000186,2.929603e+08,3.021073,9.697227e+07
8789,8789,0.084917,0.003973,93200,0.464666,2.005742e+05,0.003613,5.550951e+07
9546,9546,-1.810721,-0.795421,75100,0.000788,9.530556e+07,1.955703,4.873211e+07
5135,5135,-0.404042,-0.433493,73900,0.009476,7.799032e+06,0.175583,4.441797e+07
1212,1212,0.012560,0.094192,40100,0.290822,1.378850e+05,0.004515,3.053962e+07
...,...,...,...,...,...,...,...,...
2379,2379,-4.466583,4.447707,100,1.369681,7.300970e+01,19.866233,3.675065e+00
3304,3304,-4.143795,4.641069,100,1.408332,7.100597e+01,19.355279,3.668558e+00
7687,7687,-4.167891,4.522109,100,1.476305,6.773667e+01,18.910391,3.581982e+00
3343,3343,4.776344,-4.978566,100,1.173772,8.519545e+01,23.799787,3.579673e+00
3068,3068,4.351864,4.412940,100,1.479056,6.761071e+01,19.206380,3.520221e+00

In [10]:
dc.describe()

,id,x_coordinate,y_coordinate,money,time (hr),money_and_time_ratio,"distance_to_(0,0)","distance_money_time_ratio_(0,0)"
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,1.000000e+04,10000.000000,1.000000e+04
mean,4999.50000,-0.016431,0.037561,18430.320000,0.750245,1.377386e+05,8.327162,6.154768e+04
std,2886.89568,2.889568,2.881789,25382.131155,0.433541,3.212502e+06,5.319796,1.369983e+06
min,0.00000,-4.999292,-4.999928,100.000000,0.000032,6.668374e+01,0.001516,3.520221e+00
25%,2499.75000,-2.513854,-2.415033,900.000000,0.373141,1.489860e+03,3.911300,2.337639e+02
50%,4999.50000,-0.024904,0.010442,5800.000000,0.749218,9.921099e+03,7.932445,1.571485e+03
75%,7499.25000,2.461754,2.540303,26900.000000,1.122812,4.614359e+04,11.907404,7.501915e+03
max,9999.00000,4.999851,4.999626,102300.000000,1.499851,2.929603e+08,24.771480,9.697227e+07

In [11]:
dc100distance = dc[:100]
#dc100distance # only 100 banks to test your code

In [12]:
dc100distance

,id,x_coordinate,y_coordinate,money,time (hr),money_and_time_ratio,"distance_to_(0,0)","distance_money_time_ratio_(0,0)"
0,0,2.851925,1.201712,29700,0.273403,108630.921470,4.788794,22684.399419
1,1,4.150372,-2.654334,6500,0.064040,101499.543603,12.135539,8363.826708
2,2,-1.494092,-1.230419,89400,0.127458,701405.770444,1.873121,374458.338887
3,3,1.271326,-0.088520,96100,1.315029,73078.228687,0.812053,89991.994340
4,4,2.471113,-0.592810,41100,0.164393,250010.909373,3.228911,77428.873274
...,...,...,...,...,...,...,...,...
95,95,-3.460059,2.432256,3300,0.849209,3885.967066,8.943939,434.480508
96,96,0.679599,-1.817383,14300,1.215317,11766.482178,1.882368,6250.894009
97,97,0.578936,-4.230494,11500,0.521574,22048.652327,9.116124,2418.643184
98,98,2.963007,-4.236584,200,1.034983,193.239920,13.364028,14.459706
99,99,3.725684,0.995185,2100,0.712231,2948.479602,7.435555,396.537913

In [14]:
import numpy as np

p1 = np.array([-1.950527,-1.495858])

p2 = np.array([-1.810721,-0.795421])

a = np.linalg.norm(p1-p2)
a

0.7142532524287165

In [15]:
closest_0_0 = dc.sort_values(['distance_to_(0,0)'], ascending = True)
#closest_0_0

In [115]:
#dc['x_coordinate'] = np.radians(dc['x_coordinate'])
#dc['y_coordinate'] = np.radians(dc['y_coordinate'])

In [16]:
dist = DistanceMetric.get_metric('haversine')

In [17]:
dc100distance

,id,x_coordinate,y_coordinate,money,time (hr),money_and_time_ratio,"distance_to_(0,0)","distance_money_time_ratio_(0,0)"
0,0,2.851925,1.201712,29700,0.273403,108630.921470,4.788794,22684.399419
1,1,4.150372,-2.654334,6500,0.064040,101499.543603,12.135539,8363.826708
2,2,-1.494092,-1.230419,89400,0.127458,701405.770444,1.873121,374458.338887
3,3,1.271326,-0.088520,96100,1.315029,73078.228687,0.812053,89991.994340
4,4,2.471113,-0.592810,41100,0.164393,250010.909373,3.228911,77428.873274
...,...,...,...,...,...,...,...,...
95,95,-3.460059,2.432256,3300,0.849209,3885.967066,8.943939,434.480508
96,96,0.679599,-1.817383,14300,1.215317,11766.482178,1.882368,6250.894009
97,97,0.578936,-4.230494,11500,0.521574,22048.652327,9.116124,2418.643184
98,98,2.963007,-4.236584,200,1.034983,193.239920,13.364028,14.459706
99,99,3.725684,0.995185,2100,0.712231,2948.479602,7.435555,396.537913

In [18]:
dc100distance[['x_coordinate','y_coordinate']].to_numpy()

array([[ 2.85192525,  1.20171164],
       [ 4.15037189, -2.65433434],
       [-1.49409204, -1.23041901],
       [ 1.27132578, -0.08852046],
       [ 2.47111262, -0.59280993],
       [-3.16972627, -1.96542719],
       [ 1.93770091, -4.45186039],
       [ 4.79962434, -2.33093241],
       [ 1.74749109, -1.79191836],
       [-1.1888275 ,  1.06731165],
       [ 2.62820647, -0.22075154],
       [-1.46521107,  3.01551683],
       [ 0.23063455,  4.16197574],
       [-0.98580357, -0.49271748],
       [ 3.02053644,  1.04526368],
       [-3.63066502,  2.1142408 ],
       [-4.56719299,  4.84712978],
       [-2.50314464,  4.06718588],
       [ 0.12392157, -1.51169121],
       [ 3.28683556, -2.49379383],
       [-1.57878097, -3.02401973],
       [-2.14485214, -2.31545517],
       [ 0.10628181, -3.75773459],
       [ 3.75897733,  0.95822647],
       [ 0.74595251, -0.36300027],
       [-4.16121375, -4.44703407],
       [-4.76053752,  2.7884769 ],
       [ 1.23661912,  4.1182547 ],
       [-0.96290921, -1.33584417],
       [ 4.42867945,  1.8324997 ],
       [-0.25465704,  1.56919579],
       [ 1.70946689,  3.70572123],
       [-4.75404591, -0.04230621],
       [ 4.76966604, -4.10740988],
       [ 0.23962317, -2.71469722],
       [-2.04751448,  0.27354242],
       [-3.13129874, -4.40483316],
       [-3.84896095,  0.45164849],
       [ 2.78102425, -0.77400349],
       [ 3.57705923,  1.44917001],
       [-3.38231112, -1.34113543],
       [-0.60925291,  2.8999797 ],
       [ 0.26617978,  2.09253757],
       [ 1.68675322, -4.05487031],
       [-3.95427521, -3.97085388],
       [-4.13413197, -4.70840818],
       [ 4.91029721, -1.2532099 ],
       [-4.99376669,  4.36851585],
       [-4.07774792, -2.12431217],
       [ 3.51785814, -4.90296616],
       [-2.48535906, -3.74839245],
       [ 1.43547457, -2.94231615],
       [-2.44266859,  2.6309614 ],
       [-0.4601826 , -0.95374561],
       [-4.26484511, -3.25872948],
       [-2.80438092,  3.23552089],
       [-3.8721704 ,  0.16762778],
       [ 4.81579452, -4.82886483],
       [-1.60096827, -1.32938127],
       [-1.59542037,  4.56499994],
       [ 1.3558994 , -2.71332475],
       [-2.90094575, -1.05305192],
       [ 0.65773535,  0.06702485],
       [ 4.28147956,  4.39942399],
       [ 4.53351507, -3.86368895],
       [ 2.86225001, -2.06501119],
       [ 0.2387701 , -4.4419891 ],
       [-0.13596056, -0.47160896],
       [-2.82136448, -4.94972055],
       [ 2.93286383, -1.03412494],
       [ 2.32236314, -1.98821412],
       [ 2.25061054,  0.53188073],
       [ 4.48141729, -4.34267159],
       [-1.28762966,  0.45417591],
       [-4.00854439, -1.92256305],
       [-1.76421428, -2.39843798],
       [ 3.865929  ,  2.54256814],
       [-0.68609664, -4.01944884],
       [-4.7333672 ,  4.91128904],
       [-3.46900566, -4.21347767],
       [ 3.75475261, -4.0740651 ],
       [ 2.53044043, -0.34203307],
       [-0.61678556,  3.38724154],
       [ 4.14967741, -0.51833062],
       [ 4.28539948,  4.88129072],
       [ 1.38947434,  0.80542402],
       [-0.10596183, -4.91781152],
       [-3.50715932,  2.66670189],
       [-3.66221741,  0.99759545],
       [-4.90794673, -2.9568418 ],
       [ 2.85585957, -2.82316015],
       [ 3.86733902,  0.61466305],
       [-4.08511679, -1.36349274],
       [ 2.43815526, -1.19565684],
       [-1.77454397,  1.8394879 ],
       [-3.46005915,  2.43225579],
       [ 0.67959878, -1.81738309],
       [ 0.57893636, -4.23049425],
       [ 2.9630074 , -4.23658392],
       [ 3.72568361,  0.99518457]])

In [19]:
dist.pairwise(dc[['x_coordinate','y_coordinate']].to_numpy())

array([[0.        , 2.24913692, 1.80192502, ..., 1.26133562, 1.45305029,
        1.05318287],
       [2.24913692, 0.        , 0.57770619, ..., 1.60003936, 1.6740547 ,
        2.85858612],
       [1.80192502, 0.57770619, 0.        , ..., 1.07098139, 2.03626658,
        2.43747748],
       ...,
       [1.26133562, 1.60003936, 1.07098139, ..., 0.        , 2.67809891,
        1.36670287],
       [1.45305029, 1.6740547 , 2.03626658, ..., 2.67809891, 0.        ,
        1.72248554],
       [1.05318287, 2.85858612, 2.43747748, ..., 1.36670287, 1.72248554,
        0.        ]])

In [20]:
distace_matrix = pd.DataFrame(dist.pairwise(dc100distance[['x_coordinate','y_coordinate']].to_numpy()), columns = dc100distance.id.unique(), index = dc100distance.id.unique())

In [26]:
distace_matrix.loc[96, 90]

1.7951153158265085

In [21]:
distace_matrix

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,0.000000,2.249137,1.801925,1.374911,1.559907,2.822793,0.995019,1.779667,1.455971,2.238324,...,2.097879,1.151351,1.813524,1.931427,1.695049,1.166715,0.404373,1.952552,0.827416,0.895716
1,2.249137,0.000000,0.577706,2.314009,2.378289,1.172990,2.555005,0.645261,2.452880,0.313225,...,1.302060,1.403792,2.212638,2.096564,0.634617,1.650837,2.513945,2.049448,1.727760,1.492522
2,1.801925,0.577706,0.000000,2.803177,2.302018,1.655769,2.698188,0.086125,3.022669,0.436537,...,1.853985,0.826754,2.590265,2.350888,0.127357,1.822519,2.185853,2.225628,1.673371,0.941284
3,1.374911,2.314009,2.803177,0.000000,1.168719,1.454790,0.381542,2.887347,0.325559,2.572331,...,1.013077,2.502237,0.762491,1.026946,2.725947,1.015642,0.971104,1.170774,1.239775,2.268017
4,1.559907,2.378289,2.302018,1.168719,0.000000,1.398260,1.193698,2.223870,0.847702,2.153794,...,1.860336,1.776353,0.586273,0.464319,2.387382,2.146618,1.386046,0.410928,2.171818,1.932518
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1.166715,1.650837,1.822519,1.015642,2.146618,1.859853,0.960299,1.892435,1.338787,1.942179,...,0.977492,1.962061,1.760784,2.023912,1.718585,0.000000,1.016255,2.173731,0.398646,1.637878
96,0.404373,2.513945,2.185853,0.971104,1.386046,2.420876,0.590680,2.173734,1.067842,2.613175,...,1.795115,1.546514,1.472108,1.646527,2.069777,1.016255,0.000000,1.713237,0.814948,1.300004
97,1.952552,2.049448,2.225628,1.170774,0.410928,0.987544,1.351263,2.175599,0.862077,1.912725,...,1.547272,2.033103,0.413139,0.150970,2.348086,2.173731,1.713237,0.000000,2.384049,2.271292
98,0.827416,1.727760,1.673371,1.239775,2.171818,2.251057,1.034811,1.720136,1.528557,1.949137,...,1.371431,1.586808,1.996638,2.254659,1.549891,0.398646,0.814948,2.384049,0.000000,1.256115
99,0.895716,1.492522,0.941284,2.268017,1.932518,2.560341,1.890345,0.901045,2.319068,1.367849,...,2.464541,0.332130,2.487409,2.383820,0.860369,1.637878,1.300004,2.271292,1.256115,0.000000

In [123]:
Y = DistanceMetric.get_metric('euclidean')

In [22]:
def haversine_vectorize(x1, y1, x2, y2):
    x1, y1, x2, y2 = map(np.radians, [x1, y1, x2, y2])
    
    new_x = x2 - x1
    new_y = y2 - y1
    
    haver_formula = np.sin(new_y/2.0)**2 + np.cos(y1) * np.cos(y2) * np.sin(new_x/2.0)**2
    dist_ = 2 * np.arcsin(np.sqrt(haver_formula))
    km =  6373 * dist_ # to get dist in km
    return km

haversine_vectorize(0.022189, -0.001545, 0.043129, -0.010346)

2.526512136954726

In [24]:
Total = distace_matrix[0].sum()

In [25]:
Total

152.05594254586694